// src/components/content/rules.tsx
import * as React from "react"

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import Image from "next/image"
import mary from "@/app/images/mary.svg";
import people from "@/app/images/people.svg";
import rosary from "@/app/images/rosary.svg";
import change from "@/app/images/change.svg";
import meeting from "@/app/images/meeting.svg";
import Section from "../ui/section";

export default function Rules() {
  const cards = [
    {
      description: "Jedna róża składa się z 20 osób",
      image: people
    },
    {
      description: "Każda osoba codziennie odmawia jeden dziesiątek różańca",
      image: rosary
    },
    {
      description: "Co miesiąc wymienia się tajemniczkę u zalatora (szefa róży)",
      image: change
    },
    {
      description: "Co miesiąc na discordzie odbywa się krótkie spotkanie",
      image: meeting
    }
  ]
  return (
    <Section heading="Reguły" className="py-40 bg-right bg-no-repeat bg-hero bg-contain backdrop-blur-3xl"

      style={{backgroundImage: `url(${mary.src})`}}
    >
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5 max-w-[65em] m-auto">
      {
        cards.map((card, i) => 
          <Card className="bg-gradient-to-r from-teal-600 to-cyan-800  border-none text-white w-[16em] text-center justify-self-center" key={i}>
            <CardHeader>
              <CardTitle className="font-normal">{card.description}</CardTitle>
            </CardHeader>
            <CardContent className="flex justify-center">
              <Image src={card.image} alt="" className="invert w-[12em]"/>
            </CardContent>
          </Card>
        )
      }
      </div>
    </Section>
  )
}

// src/lib/sections/rules.svelte
<script>
	import Section from '$lib/ui/section.svelte';
	import Card from '$lib/ui/card.svelte';

	const cards = [
		{
			description: 'Jedna róża składa się z 20 osób',
			image: '/images/people.svg'
		},
		{
			description: 'Każda osoba codziennie odmawia jeden dziesiątek różańca',
			image: '/images/rosary.svg'
		},
		{
			description: 'Co miesiąc wymienia się tajemniczkę u zalatora (szefa róży)',
			image: '/images/change.svg'
		},
		{
			description: 'Co miesiąc na discordzie odbywa się krótkie spotkanie',
			image: '/images/meeting.svg'
		}
	];
</script>

<Section
	heading="Reguły"
	classes="py-40 bg-right bg-no-repeat bg-hero bg-contain backdrop-blur-3xl"
>
	<div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5 max-w-[65em] m-auto">
		{#each cards as card}
			<Card
				classes="bg-gradient-to-r from-teal-600 to-cyan-800  border-none text-white w-[16em] text-center justify-self-center"
			>
				<div class="flex flex-col space-y-1.5 p-6">
					<h3 class="font-normalleading-none tracking-tight">
						{card.description}
					</h3>
				</div>

				<div class="p-6 pt-0 flex justify-center">
					<img src={card.image} alt="" class="invert w-[12em]" />
				</div>
			</Card>
		{/each}
	</div>
</Section>
