// src/lib/ui/section.svelte
<script>
    export let classes = "";
    export let id = "";
    export let style = "";
    export let headerClasses = "";
    export let heading = "";
</script>

    <section
      class={"p-6 relative z-10 bg-primary "+classes}
      id={id}
      style={style}
    >
      <h2 class={"uppercase text-5xl font-extrabold text-b text-center mb-8 "+ headerClasses}>{heading}</h2>
        <slot/>
    </section>

// src/components/ui/section.tsx
import { cn } from "@/lib/utils"
import * as React from "react"

type SectionProps = {
  heading: string,
  className?: string
  style?: React.CSSProperties,
  headerClass?: string,
  id?: string
}

export default function Section(props: React.PropsWithChildren<SectionProps>) {
  return (
    <section
      className={cn(
        "p-6 relative z-10 bg-primary",
        props.className
      )}
      id={props.id}
      style={props.style}
    >
      <h2 className={cn("uppercase text-5xl font-extrabold text-b text-center mb-8", props.headerClass)}>{props.heading}</h2>
      {props.children}
    </section>
  )
}
